### ISSUE TITLE
Use a variadic function in Utilities and changeTag()

### ISSUE THREAD

**Issue by AwesomePossum212** [AwesomePossum212/nametag-plus#19]
**Is your feature request related to a problem? Please describe.**
Currently, changeTag can only change one element at a time. The bottleneck appears to be in Utilities, where the function only accepts one property table.

**Describe the solution you'd like**
By using a variadic function (and adjusting the code appropriately), a theoretically unlimited number of arguments can be passed to changeTag. For example:
**Old**
````
module.changeTag(tag, propTable1)
module.changeTag(tag, propTable2)
module.changeTag(tag, propTable3)
````
**New**
````
module.changeTag(tag, propTable1, propTable2, propTable3)
````

**Describe alternatives you've considered**
Originally in early development, the plan was to create a batch change function. However, this was scrapped because the batch changing behavior would be the same on the backend as just calling .changeTag() multiple times.

**Additional context**
Reference article on the Developer Hub: https://developer.roblox.com/en-us/articles/Variadic-Functions

**Comment by Water261** [comment]
Working on this, will open a pull request and explain how it works.

**Comment by Water261** [comment]
The branch this is being developed on is here: https://github.com/Water261/nametag-plus/tree/variadic_functions

**Comment by Water261** [comment]
^ Above branch was merged to my main branch, is currently in a pull request.

**Comment by AwesomePossum212** [comment]
Forgot to close this a while back.
